---
title: "Dynamique d'opinions"
author: "Robin Delabays"
date: today
format: pdf
---

Je vais prendre un exemple où il n'y a que deux opinions possibles pour simplifier les explications. 
Nous pourrons discuter de comment étendre cela à plus d'opinions si nécessaire. 
Toutes les valeurs ci-dessous sont juste là à titre d'exemple, il faudra les adapter selon les résultats de ton sondage. 

# Construction de la matrice de transition
*Prérequis : Probabilités*

Le sondage va nous servir à construire une matrice qui contient les probabilités de passer d'une opinion à une autre. 

Supposons donc qu'il y a deux opinions possibles : "pour" le nucléaire et "contre" le nucléaire. 
Supposons aussi que tu fais passer le sondage à 20 personnes. 

Lors du premier sondage, 12 personnes se déclarent "pour" et 8 personnes se déclarent "contre". 
Tu les exposes ensuite à la sensibilisation, puis tu leur fait passer le deuxième sondage. 
Cette fois-ci, tu as 10 personnes "pour" et 10 personnes "contre". 
Certaines personnes ont donc changé d'avis. 

Mais en réalité, tu as un peu plus d'information que ce que j'ai décrit ci-dessus. 
Comme tu as l'identité des sondé·es, tu peux savoir que :

- 8 personnes qui étaient "pour" au premier tour sont toujours "pour" au second tour ;
- 4 personnes qui étaient "pour" au premier tour sont maintenant "contre" ; 
- 2 personnes qui étaient "contre" au premier tour sont maintentant "pour" ;
- 6 personnes qui étaient "contre" sont restées "contre" au second tour.

On peut résumer tout cela dans un tableau :

|   |"pour" au 1er tour|"contre" au 1er tour|
|---|---               |---                 |
|"pour" au 2e tour|8  |2  |
|"contre" au 2e tour|4  |6  |

ou sous forme de poucentages

|   |"pour" au 1er tour|"contre" au 1er tour|
|---|---               |---                 |
|"pour" au 2e tour|0.67  |0.25  |
|"contre" au 2e tour|0.33  |0.75  |
|   |---|---|
|   |1.0|1.0|

La première case me donne donc le pourcentage de personnes qui étaient "pour" au 2e tour, parmis celles qui étaient "pour" au premier tour. 
La case dans la 2e ligne, 1ère colone me donne le pourcentage de personnes qui étaient "contre" au 2e tour, parmis celles qui étaient "pour" au 1er tour. 
Et ainsi de suite pour les autres cases. 

Je peux résumer tout cela dans une matrice :

$$
 M = 
 \begin{pmatrix}
  0.67 & 0.25 \\
  0.33 & 0.75
 \end{pmatrix}
$$

Chaque élément de cette matrice correspond à un probabilité de passer d'une opinion à un autre.

# Modéliser la dynamique des opinions
*Prérequis : Matrices et vecteurs*

La matrice $M$ construite ci-dessus m'indique la probabilité de passer d'une opinion à une autre après avoir été sensibilisé·e au sujet. 
Nous allons maintenant extrapoler les résultats du sondage à une grande population. 

Imaginons maintenant que nous voulons décrire l'évolution des opinions d'une population de 1000 personnes. 
Supposons aussi qu'au départ, 500 personnes sont "pour" et 500 personnes sont "contre". 
Selon notre sondage, on peut s'attendre à ce qu'après la sensibilisation, le nombre de personnes qui étaient "pour" au départ et sont toujours "pour" à la fin est de $500\cdot 0.67 \approx 335$. 
Du coup, on sait que 165 personnes sont passées de "pour" à "contre". 
De manière similaire, on a 125 personnes (500*0.25) qui sont passées de "contre" à "pour" et donc 375 personnes qui sont passées de "contre" à "contre". 

Donc après une séance de sensibilisation, dans notre population de 1000 personnes, il y a $335+125 = 460$ personnes "pour" et $165+375 = 540$ personnes "contre". 

Une bonne manière d'écrire cela mathématiquement est de mettre la population dans un vecteur selon leurs opinions initiales :
$$
 \vec{v}_0 = 
 \begin{pmatrix}
  500\\
  500
 \end{pmatrix}
$$
De cette manière, on peut trouver le nombre de personnes dans chaque opinion grâce à la multiplication matrice-vecteur :
$$
 \vec{v}_1 = 
 \begin{pmatrix}
  0.67 & 0.25\\
  0.33 & 0.75
 \end{pmatrix}
 \cdot
 \begin{pmatrix}
  500\\
  500
 \end{pmatrix}
 = 
 \begin{pmatrix}
  460\\
  540
 \end{pmatrix}
$$

Maintenant, si soumet cette même population à une nouvelle sensibilisation, que se passera-t-il ? 
On peut imaginer que les opinions changeront à nouveau.
Et selon notre sondage, les nouvelles opinions seraient :
$$
 \vec{v}_2 =
 \begin{pmatrix}
  0.67 & 0.25\\
  0.33 & 0.75
 \end{pmatrix}
 \cdot
 \begin{pmatrix}
  460\\
  540
 \end{pmatrix}
 \approx 
 \begin{pmatrix}
  443\\
  557
 \end{pmatrix}
$$
Et on pourrait facilement continuer comme pour autant de sensibilisation que nous le souhaitons. 

# Pour conclure
Cette méthode est loin d'être parfaite. 
On peut difficilement garantir qu'elle décrit bien l'évolution des opinions dans une population. 
Cependant, elle vaut mieux que rien et se base sur des données assez simples à récolter (ton sondage). 

De plus, on peut montrer que si on répète le processus "sensibilisation" $\to$ "changement d'opinion" beaucoup de fois, les population dans chaque opinion finissent par se stabiliser à un valeur fixe. 
On pourrait imaginer qu'il s'agit là des opinions qu'aurait un population qui est bien informée (c'est-à-dire qui a été beaucoup sensibilisée). 
Je peux te donner les détails de comment voir ça, mais ça rajoutera des maths, donc à toi de me dire ;-)
